### ISSUE TITLE
addressbook with self-hosted non-Peppol identities [1]

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/peppol-php#139]

**Comment by yasharpm** [comment]
Done in this [commit](https://github.com/pondersource/peppol-php/commit/8a23d26f7b8fc37329519e0f4770e72fe198a2c6).
New contacts are saved in the default address book. Fortunately it supports custom fields. The users can only see the custom fields inside the peppolnext app.
Contacts are either "suppliers" or "customers". The separation made sense to me since you don't necessarily want to receive invoices from your customers! In the logic, a contact can be flagged as both, but the UI only creates either one.
We have no options to remove or edit a contact. I assume it can come later and doesn't count as "minimum viable"!
